// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swtpoysfvdjuskyngebc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dHBveXNmdmRqdXNreW5nZWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzM5MjcsImV4cCI6MjA2ODQwOTkyN30.vek6yo_7CaRJgDQ21gRZjFxwu38DPrIPGcTLB0i-Z3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});